initial-signup 회원가입기능구현,db통일
wecode-bootcamp-korea/42-1st-ASAP-backend pull request #5
Opened 2023-02-08 10:23 UTC by wkc28

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ v ] 기능 추가
- [ v ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 
- db 무사히 이식 , 통일작업 완료

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- users/signup 이라는 엔드포인트 지정
-포트값을 지정 Server통신확인 

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 앞으로 많은 기능구현을 각자해서 나중에 합칠텐데 기능구현 테스트를 위해 db에 값을 각자 입력하게되도 나중에 충돌이 안날까요??

2023-02-09 02:32 UTC, sangwoong03 requested changes
고생하셨습니다 원경님!
이번 리뷰에 대한 수정 요청 사항 및 원경님이 추가로 구현하시는 사항도 포함하여 push 해주세요~!

API flow에 대해 감이 잘 잡히지 않는다면, 실제 서비스를 이용하는 유저 입장에서 pseudo-code(가짜 코드)를 작성해보는 것도 좋은 방법입니다.
pseudo-code(가짜 코드)는 프로그래밍 언어로 작성하는 코드가 아닌, 내가 알아보기 쉬운 언어로 대체하여 작성해보는 코드입니다.

```
예시))
1. 유저가 메인페이지에 접속한다.
2. 회원가입 버튼을 클릭한다.
3. 이름, 성, 이메일, 비밀번호, 피부타입을 작성한다.
4. 회원가입 버튼을 누른다.
....
```

이 때 각각의 flow에 대해 Backend에서 처리해야 하는 데이터 혹은 로직은 어떤 것이 있을지 고민해보면 훨씬 수월하게 API를 구현할 수 있을 것 같습니다.

2023-02-09 02:32 UTC, sangwoong03 commented on package.json
> +    "dbmate": "^1.16.1",
지금 `dependecies`에 추가된 dbmate 모듈은 node로 개발된 모듈 중 하나입니다.

현재 개발을 하면서 Database에 설계된 스키마를 바탕으로 테이블을 생성하기 위해 사용하는 dbmate는 MySQL과 같은 클라이언트라고 생각하시면 됩니다. (brew로 설치)

따라서 해당 모듈을 현재 개발 단계에서 필요가 없으니 삭제해주시면 됩니다.

```
npm uninstall dbmate
```

2023-02-09 02:32 UTC, sangwoong03 commented on controller/user-controller.js
> +    res.status(201).end();
회원가입이 완료되었음을 클리이언트 (프론트엔드 개발자)에게 알리는 메시지를 전달하도록 수정해주세요.

```suggestion
    return res.status(201).send({ message : "SIGNUP_SUCCESS" });
```

2023-02-09 02:32 UTC, sangwoong03 commented on controller/user-controller.js
> +module.exports = { signUp };
작성한 모듈을 내보내기 위한 코드를 좀 더 가독성을 높게 작성하는 방법은 다음과 같습니다.

하나의 파일 내부에 하나의 모듈만 존재할 수도 있고, 여러개의 모듈이 존재할 수도 있습니다.

경우에 따라 아래와 같이 작성해주시면 좋을 것 같습니다.

다른 부분에서도 해당 내용을 확인하여 적용해주세요!

```suggestion
// 모듈이 하나인 경우
// 중괄호 시작과 닫는 부분에 띄어쓰기를 넣어 모듈이 한눈에 모이도록 작성
module.exports = { signUp };

// 모듈이 하나 이상인 경우
module.exports = {
  signUp,
  signIn
};
```

2023-02-09 02:32 UTC, sangwoong03 commented on services/user-services.js
> +}
- 회원가입과 관련된 서비스 단의 함수 이름을 조금 더 명확하게 작성해주면 좋을 것 같습니다.
새로운 유저 정보를 생성하는 API의 비즈니스 로직이기 때문에 postUsers보다는 아래와 같은 함수명이 명확해보입니다.

- 함수의 arguments로 유저가 회원가입 시 보낸 데이터를 포함해주어야 합니다.

- 추가로 비밀번호는 bcrypt 모듈을 통해 암호화를 할 수 있는 코드를 추가해주세요.
```suggestion
const createUser = async(lastName, firstName, email, password, skinType) => {
  // bcrypt 모듈을 통한 비밀번호 암호화 로직 추가
```

2023-02-09 02:32 UTC, sangwoong03 commented on controller/user-controller.js
> +    const {email, password, firstname, lastname} =req.body;
- JavaScript는 일반적으로 띄어쓰기를 구분할 때 camelCase로 작성합니다.
- 추가로 skinType도 회원가입을 할 때 받는 데이터입니다. 해당 데이터도 받아오도록 수정해주세요.
- 필수로 데이터베이스에 저장되어야 하는 데이터가 정상적으로 request 객체에 포함되지 않았을 경우 예외처리를 해주세요.
`req` 객체 내부에서 특정 `key`에 대한 `value`(데이터)가 없는 경우 `Key Error`를 반환하도록 작성해주세요.
이 때 skinType은 null 값을 허용토록 스키마를 설계했기 때문에 반드시 예외처리를 하지 않아도 될 것 같습니다.

```suggestion
    const {email, password, firstName, lastName, skinType} =req.body;
    
    if ( !email || !password || !firstName || !lastName) {
      throw new Error("Key Error!");
    }
```

2023-02-09 23:44 UTC, sangwoong03 requested changes

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +    }
두 코드의 순서를 바꿔주세요.

service레이어의 함수의 인자로 데이터를 전달하기 전에 해당 데이터들이 request 객체에 제대로 포함되어 있는지 확인하는 코드가 우선되어야 합니다.

```suggestion
    if (!email|| !password || !firstname || !lastname){
      throw new Error("KEY Error!");
    };
    
    await userService.signUp(email, password, firstname, lastname, skintype);
```

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +  }catch (err) {
마이너한 수정 (공백을 통해 가독성을 높여주세요.)
```suggestion
  } catch (err) {
```

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +   }
signIn 함수와 마찬가지로, 위 두가지 코드 순서가 변경되어야 할 것 같습니다.
그리고 오타가 있으니, push 전에 postman을 활용하여 api가 잘 동작하는지 확인해주는 것도 좋으니 참고해주세요~!

```suggestion
   if( !email || !password ){
    throw new Error("SIGN_IN_FAILED!");
   };
   
   const accessToken = await userService.signIn(email, password);
```

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +    res.status(er.statusCode || 400).json ({message: err.message});
해당 부분에도 오탈자가 있네요~!
프로그래밍의 치명적인 오류는 쉽게 찾을 수 없는 오타 (Human error)에서 비롯될 수 있으니, 반드시 내가 작성한 코드가 올바르게 동작하는지 다양한 툴을 이용하여 테스트하는 것도 중요합니다!

```suggestion
    res.status(err.statusCode || 400).json({message: err.message});
```

2023-02-09 23:44 UTC, sangwoong03 commented on models/dataSource.js
> +      console.error("Failed to connect to Database")
- 해당 코드를 TypeOrm 공식문서에서 제공하는 포맷과 동일하게 잘 작성해주셨습니다.
- 다만 아쉬운 점은, tab을 이용한 들여쓰기와 스페이스바를 이용한 공백처리가 모두 포함되어 있는 것 같습니다.
동일한 코드 블록을 가리키기 위해 동일한 들여쓰기를 지키며 코드를 작성하는 것도 가독성을 유지하는데 중요한 요소이기 때문에 이 부분도 반드시 확인해주세요~!
```suggestion
appDataSource.initialize()
  .then(() => {
    console.log("Data Source has been initialized!")
  })
  .catch((err)=> {
    console.error("Failed to connect to Database")
```

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +
불필요한 공백은 지워주세요

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +  res.status(err.statusCode || 400).json({message: err.message});
들여쓰기를 통해 `catch(err) { ... }` 구문 내부에서 실행되는 코드임을 명시해주세요
 ```suggestion
      res.status(err.statusCode || 400).json({message: err.message});
```

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +
불필요한 공백은 지워주세요~!

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +
불필요한 공백은 지워주세요~!

2023-02-09 23:44 UTC, sangwoong03 commented on controller/user-controller.js
> +   }
- 25번 라인 코드와 28~30번 라인의 코드의 순서가 바뀌어야 합니다.
이메일과 패스워드에 대한 데이터가 없을 때엔 `accessToken`을 발급하지 못하고 Key error를 반환해야 하기 때문입니다.

- 또한 불필요한 공백은 삭제해주세요. (26번 라인과 27번 라인 모두 공백일 필요는 없습니다. 코드를 구분하기 위해 공백을 두는 경우는 한줄만 띄워주세요.)

- 어제 구두로 설명드린 바와 같이 작성해주신 `if { ... }`  구문을 보면 같은 코드 블럭임에도 불구하고 들여쓰기가  맞지 않습니다. 해당 부분도 신경써서 수정해주세요.
```suggestion
   if( !email || !password ){
      throw new Error("SIGN IN FAILED!");
   }
   
    const accessToken = await userService.signIn(email,password);

```

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +
불필요한 공백은 삭제해주세요

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +
해당 부분도 불필요한 공백인 것 같습니다
try{ } 구문 뒤에서 바로 return 하도록 수정해주세요

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +    throw error;
해당 코드 라인을 보면 들여쓰기가 하나도 적용되어 있지 않습니다.
어떤 부분이 하위 코드 블럭의 내용인지 한눈에 보기 어렵습니다.

어제 구두로 설명드린 내용을 적용할 수 있도록 꼼꼼하게 확인해주세요

```suggestion
    return AppDataSource.query(
      `
      INSERT INTO users (
        email,
        password, 
        first_name,
        last_name,
        skin_type
      ) VALUES (
        ?,
        ?,
        ?,
        ?,
        ?
      )
      `, 
        [email, password, firstname, lastname, skintype]
      );
    } catch(err) {
      const error= new Error('INVAID_DATA_INPUT');
      error.statusCode = 500;
      throw error;
```

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +
불필요한 공백 삭제

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +  const createuser = async (email, password, firstname, lastname, skintype) => {
JavaScript 언어의 컨벤션 중 하나는 camelCase를 지키는 것입니다.
camelCase는 띄어쓰기 혹은 언더바(_)로 단어를 구분하는 것이 아니라 대문자로 띄어쓰는 부분을 구분하는 작성 방법입니다.
```suggestion
  const createUser = async (email, password, firstname, lastname, skintype) => {
```

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +const connectuser = async (email) => {
함수나 변수명은 그 대상의 행위와 예측 결과를 알 수 있도록 작명해주는 것이 좋습니다.

현재 해당 함수는 user의 이메일 정보를 받아 유저의 데이터를 확인하는 함수이기 때문에 아래와 같이 수정해주세요.

```suggestion
const getUserrByEmail = async (email) => {
```

2023-02-09 23:44 UTC, sangwoong03 commented on models/user.dao.js
> +      u.id
유저의 id 정보만 파악하면 email 혹은 password에 대한 정보를 확인할 수 없을 것 같습니다.
다른 컬럼에 대한 데이터도 받아올 수 있도록 수정해주세요.

```suggestion
      u.id,
      u.email,
      u.password
```

2023-02-09 23:44 UTC, sangwoong03 commented on validators.js
> +const checkEmail = (email) => {
이메일의 무엇을 확인하는지 조금 애매한 함수명 같습니다.
이메일 데이터에 대해 형식이 올바른지 유효성검사를 하는 함수이기 때문에 다음과 같이 수정해주세요.
```suggestion
const validateEmail = (email) => {
```

2023-02-09 23:44 UTC, sangwoong03 commented on validators.js
> +  const re = new RegExp(
re라는 변수명을 통해 어떤 값이 할당되었는지 예측할 수 없습니다.

변수를 선언한 이후 실제 `re`라는 변수를 사용할 때 혹은 다른 동료 개발자가 해당 변수를 보았을 떄 그 의미가 명확하게 전달될 수 있도록 수정해주세요. (해당 부분은 다음부터 꼼꼼하게 확인해주세요.)

해당 부분은 이메일 형식의 유효성검사를 위한 정규표현식이 할당되기 떄문에 다음과 같이 설정할 수 있습니다.

변수를 어떻게 정해야 할 지 모르겠다면 아래의 방법을 참고해주세요.

1. 해당 변수 혹은 함수가 어떤 행위를 하고 어떤 결과를 보이는지 파악하기
2. 팀에서 변수명을 지을 때 어떻게 짓는지 팀 컨벤션 확인하기
3. 팀원에게 도움 요청하기

```suggestion
  const emailRegex = new RegExp(
```

2023-02-09 23:44 UTC, sangwoong03 commented on validators.js
> +const checkPassword = (password) => {
- 비밀번호 유효성 검사를 하는 부분도 위의 리뷰를 기반으로 수정해주세요.
- 15번 ~ 17번 라인은 들여쓰기도 수정해주세요.

2023-02-09 23:44 UTC, sangwoong03 commented on validators.js
> + }
위 validator.js 파일은 utils라는 폴더를 새로 생성하여 해당 폴더 내부에서 관리해주면 좋을 것 같습니다.

app.js와 동일한 경로에서 utils라는 폴더를 생성 후 해당 파일을 옮겨주세요.

2023-02-09 23:44 UTC, sangwoong03 commented on services/user-services.js
> +  await checkEmail(email)
비밀번호의 유효성검사를를 확인하는 로직도 추가해주세요.

2023-02-09 23:44 UTC, sangwoong03 commented on services/user-services.js
> +  }
분명 동일한 코드 블럭 내부의 코드인데도 들여쓰기가 상이하여 코드 파악을 한눈에 하기 어려울 것 같습니다.
다시 한 번 전체적으로 확인해주세요.

2023-02-09 23:44 UTC, sangwoong03 commented on services/user-services.js
> +  await userDao.createuser(email, hashedPassword, firstname, lastname, skintype);
함수가 종료되는 부분에서 return 키워드를 통해 그 이후의 의도치 않은 코드가 실행되지 않도록 수정해주세요
```suggestion
  return await userDao.createuser(email, hashedPassword, firstname, lastname, skintype); 
```

2023-02-09 23:44 UTC, sangwoong03 commented on services/user-services.js
> +  return jwt.sign({ sub: user.id, email:user.email }, process.env.JWT_SECRET);
jwt의 payload에는 유저의 민감한 정보를 포함하지 않습니다.
민감한 정보라고 한다면 다음과 같습니다:
- 유저의 이메일
- 유저의 비밀번호
- 유저의 이름
등 유저에 대한 개인 정보를 포함합니다.

우리는 데이터베이스의 테이블에서 유저를 특정할 수 있는 고유 값이면서 아무 의미가 없는 숫자로 이루어진 데이터를 가지고 있습니다.
바로 id 값입니다.

지금처럼 jwt 모듈에서 기본적으로 제공하고 있는 claim에 유저의 `id`를 포함하는 것도 좋지만, custom cliam을 새로 설정할 수 있습니다. 아래 코드를 참고해주세요.

아래 문서를 통해 확인해보면 더 좋을 것 같습니다.
https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims

```suggestion
  return jwt.sign({ userId: user.id }, process.env.JWT_SECRET);
```

2023-02-09 23:46 UTC, sangwoong03 commented
🙏🙏🙏🙏 원경님 리뷰 확인 간 반드시 해당 부분도 확인해주세요. 🙏🙏🙏🙏

리뷰는 총 25개입니다. 리뷰가 보이지 않는 부분은 아래 버튼을 통해 확인해주세요!!!!!

<img width="370" alt="image" src="https://user-images.githubusercontent.com/93123657/217964060-72c7b530-7057-4913-85c6-2dc6aa8c3c32.png">

2023-02-10 08:20 UTC, wkc28 commented
상웅님 수정요청사항 살펴본후 리푸시했습니다. 
이해가 안되는부분이 비밀번호의 유효성검사의 필요성과
지금 제가 작성한 로그인 구현에서 같이 tostring()을 bcrypt compaer 의  인자값에 붙여서 해결했는데 비밀번호를 알맞게 시도해도 invalid password라고 오류가 나옵니다 코드의 흐름에 문제가 있는지 리뷰를 한번 받아보고싶습니다.

2023-02-12 06:43 UTC, sangwoong03 requested changes

2023-02-12 06:43 UTC, sangwoong03 commented on models/user.dao.js
> +    try { return AppDataSource.query(
라인브레이킹 해주세요

```suggestion
    try {
      return AppDataSource.query(
```

2023-02-12 06:43 UTC, sangwoong03 commented on controller/user-controller.js
> +    const {email, password, firstname, lastname, skintype} =req.body;
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
    const {email, password, firstname, lastname, skintype} = req.body;
```

2023-02-12 06:43 UTC, sangwoong03 commented on controller/user-controller.js
> +    if (!email|| !password || !firstname || !lastname) {
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
    if (!email || !password || !firstname || !lastname) {
```

2023-02-12 06:43 UTC, sangwoong03 commented on controller/user-controller.js
> +    const { email, password }= req.body;
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
    const { email, password } = req.body;
```

2023-02-12 06:43 UTC, sangwoong03 commented on controller/user-controller.js
> +    if( !email || !password ){
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
    if( !email || !password ) {
```

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +const { validateEmail }  = require('../../util/validators');
원경님~ 지금 코드 변경사항에 util 폴더와 해당 폴더 내부에서 생성된 모듈이 보이지 않습니다.

코드를 push하기 전에 아래 사항을 반드시 확인해주세요.
1. 서버가 정상적으로 동작하는지 확인 (ping 엔드포인트 요청 시 pong 메시지 반환 확인)
2. 개발한 API의 결과값이 의도된 대로 반환되는지 확인 (postman을 이용)
3. 프론트엔드 개발자분들과 http 통신을 통해 postman으로 파악되지 않은 오류 확인 및 수정
4. 불필요한 `console.log()`와 공백 없는지 확인,  코드 포맷 확인.

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +   await validateEmail(email)
validateEmail 모듈을 확인할 수 없어서 온전한 피드백이 불가능합니다.
해당 모듈이 포함된 파일 및 폴더를 다시 한번 확인해주시고 push해주세요.

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +   if (user){
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
   if (user) {
```

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +
불필요한 공백 삭제해주세요
```suggestion
```

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +   if(!result){
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
   if (!result) {
```

2023-02-12 06:43 UTC, sangwoong03 commented on services/user-services.js
> +   return jwt.sign({userId: user.id }, progress.env.JWT_SECRET);
마이너하지만 해당 부분은 지속 언급드린 사항과 동일합니다~!
코드 포맷 자체의 통일성을 위해서도 지속 확인해주세요
```suggestion
   return jwt.sign({userId: user.id}, progress.env.JWT_SECRET);
```

2023-02-12 09:11 UTC, sangwoong03 commented
원경님! 코드의 포매팅 혹은 라인 브레이킹이 아직 어렵고 익숙하지 않다면 `prettier`를 적용해보는 것도 좋을 것 같습니다!

westudy 자료 중 prettier와 관련된 내용이 있으니 학습 후 적용해보세요! 

[링크 이동](https://study.wecode.co.kr/session/content/393)

2023-02-13 10:09 UTC, sangwoong03 approved these changes
LGTM 👍

2023-02-13 10:09 UTC, merged