[42기 장주성] [ADD] 제품 서브카테고리, 상세페이지 조회 기능 추가 | Feature/products juseong
wecode-bootcamp-korea/42-1st-ASAP-backend pull request #6
Opened 2023-02-09 07:15 UTC by jangjuseong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 제품 서브카테고리, 상세페이지 조회 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 제품 서브카테고리, 상세페이지 조회 기능 추가

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-02-09 23:49 UTC, sangwoong03 requested changes
주성님 어제 구두로 설명 드린 부분으로 변경 후 다시 push 해주시면 확인하겠습니다~!

2023-02-10 06:04 UTC, sangwoong03 requested changes
주성님 우선 엔드포인트 관련된 내용만 수정해보시고 이따가 같이 논의해보면 좋을 것 같습니다!

2023-02-10 06:04 UTC, sangwoong03 commented on routes/index.js
> +router.use('/', productRouter.router);
routes/index.js 파일은 각각의 리소스 라우터로 이동하기 위해 첫 분기처리를 해주는 역할이라고 보시면 됩니다.

따라서 products에 대한 리소스를 가리킬 수 있도록 수정해주세요.
```suggestion
router.use('/products', productRouter.router);
```

2023-02-10 06:04 UTC, sangwoong03 commented on routes/productRouter.js
> +router.get('/products/detail', productController.getProductById);
index.js 파일을 통해 라우터가 이미 한차례 분기처리 된 이후의 리소스를 포함한 엔드포인트를 설계할 수 있습니다.

- 이미 `/products` 라는 path가 설정되어 있기 때문에 products를 한번 더 작성할 필요가 없습니다. 또한 카테고리 별 상품을 조회하는 것은 `필터링`을 통해 구현해볼 수 있을 것 같습니다.

- body-hand/hand 와 body-hand/body와 관련된 엔드포인트 설계는 다시 한번 고려해 볼 필요가 있어보입니다. 지금은 body-hand 제품만 포함하고 있지만, 더 많은 상품을 카테고리별로 엔드포인트를 구분한다면 이는 비효율적인 작업을 초래할 수도 있습니다. `body-hand`를 포함하고 있는 가장 큰 범주 (테이블 명)에 따른 id 값을 path-parameter로 조회하는 것은 어떨까요?

- 상품의 상세 페이지 내부에서 상세 정보를 확인할 수 있는 엔드포인트에서도 products라는 리소를 명시하는 것이 아니라 `productId`를 path parameter로 받도록 수정해주면 좋을 것 같습니다.

```suggestion
router.get('/', productController.getProductsForMainPage);
router.get('/body-hand/hand', productController.getProductsForHands);
router.get('/body-hand/body', productController.getProductsForBodys);
router.get('/detail/:productId', productController.getProductById);
```

2023-02-13 02:55 UTC, sangwoong03 reviewed
주성님! 긴 쿼리문을 작성하느라 고생하셨습니다.

우선 1차 피드백만 반영해주세요!
추가로 쿼리문에 대한 결과를 스크린샷을 포함하여 올려주시면 감사하겠습니다.

2023-02-13 02:55 UTC, sangwoong03 commented on controllers/productController.js
> +  const limitValue = req.query.limit;
구조분해할당을 사용하면 코드를 줄일 수 있습니다.
페이지네이션 구현을 위해 limit 값을 받아오는데 새로운 변수에 할당하지 말고 바로 사용해도 좋습니다.
```suggestion
  const { formulation, scent, limit } = req.query;
```

2023-02-13 02:55 UTC, sangwoong03 commented on controllers/productController.js
> +  const limitValue = req.query.limit;
새 변수에 할당하지 않아도 됩니다.
```suggestion
  const { limit } = req.query;
```

2023-02-13 02:55 UTC, sangwoong03 commented on services/productService.js
> +    limitResult = `ORDER BY RAND() LIMIT ${limitValue}`;
`RAND()` 함수를 사용하는 이유가 있나요?

2023-02-13 02:55 UTC, sangwoong03 commented on models/productDao.js
> +      sub_cat.name AS main_category,
클라이언트에서 데이터를 받을 때 snake_case로 key 값을 받기로 논의하신 건가요?!

2023-02-13 02:55 UTC, sangwoong03 commented on services/productService.js
> +  }
dao함수의 인자로 쿼리문을 넘기는 것 보다, 데이터만 넘겨서 dao 함수 내부로 이동해주면 좋을 것 같습니다!

2023-02-13 03:00 UTC, jangjuseong commented on services/productService.js
> +    limitResult = `ORDER BY RAND() LIMIT ${limitValue}`;
메인페이지의 상품을 랜덤으로 출력하게끔 하기 위해서 넣었습니다

2023-02-13 03:48 UTC, jangjuseong commented on models/productDao.js
> +      sub_cat.name AS main_category,
네 snake case로 전달하기로 논의 완료 했습니다!

2023-02-13 03:51 UTC, jangjuseong commented on services/productService.js
> +  }
dao함수의 인자로 쿼리문을 넘기지 않고 데이터만 넘겼을 경우에, filtering 조건이 없을 경우 쿼리문에 AND pfm.formulation like "% %" 와 같은 인자가 남게 되어서 쿼리문 전체를 넘기는 방식을 택했습니다. 이와 관련해서 데이터만 넘기는 해결 방법이 있을까요?

2023-02-13 04:49 UTC, sangwoong03 commented on services/productService.js
> +  }
데이터를 넘겨서 쿼리문을 생성하는 쿼리 빌더가 dao 레이어 각 함수에 존재하면 될 것 같습니다.

2023-02-14 00:17 UTC, sangwoong03 approved these changes
LGTM 👍

2023-02-14 00:17 UTC, merged